apiVersion: v2
name: grafana
description: Helm chart to deploy Grafana via Argo CD
type: application
version: 0.1.0
appVersion: "10.2.3"   # match your Grafana version
dependencies:
  - name: grafana
    version: "8.0.0"
    repository: "https://grafana.github.io/helm-charts"
