source:
  repoURL: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetRevision: 61.2.0
  helm:
    parameters:
      - name: grafana.service.type
        value: NodePort
      - name: grafana.service.nodePort
        value: 31489
      - name: prometheus.service.type
        value: NodePort
      - name: prometheus.service.nodePort
        value: 31395
    skipCrds: true   # prevent Helm from re‑applying CRDs

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - Replace=true
    - ServerSideApply=true
