grafana:
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 32000        # Grafana exposed on 192.168.56.10:32000
  persistence:
    enabled: true
    size: 5Gi

prometheus:
  service:
    type: NodePort
    nodePort: 32001        # Prometheus exposed on 192.168.56.10:32001
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
