apiVersion: v2
name: prometheus
description: Helm chart for Prometheus
type: application
version: 0.1.0
appVersion: "v3.14.0"
dependencies:
  - name: prometheus
    version: "29.31.1"
    repository: "https://prometheus-community.github.io/helm-charts"
