prometheus:
  server:
    service:
      type: NodePort
      servicePort: 80
      nodePort: 32001

    persistentVolume:
      enabled: true
      storageClass: local-path
      size: 20Gi

    retention: 30d

  alertmanager:
    enabled: false

  kube-state-metrics:
    enabled: true

  prometheus-node-exporter:
    enabled: true

  prometheus-pushgateway:
    enabled: false
